/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demoprocessproductsales;

import java.io.FileWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.io.*;

/**
 *
 * @author lab_services_student
 */
public class processproductSales extends javax.swing.JFrame {

    String message;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(processproductSales.class.getName());
    int[][] productSales = {
        {300, 150, 700},
        {250, 200, 600},};
    ProductSales salesMethods = new ProductSales();

    /**
     * Creates new form processproductSales
     */
    public processproductSales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuLoad = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuClear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Sales Application");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadButton.setText("Load Product Data");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        saveButton.setText("Save Product Data");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel1.setText("Years Processed:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jMenu1.setText("File");

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");

        menuLoad.setText("Load Product data");
        menuLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoadActionPerformed(evt);
            }
        });
        jMenu2.add(menuLoad);

        menuSave.setText("Save product data");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        jMenu2.add(menuSave);

        menuClear.setText("Clear");
        menuClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClearActionPerformed(evt);
            }
        });
        jMenu2.add(menuClear);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
        long roundedAverage = Math.round(salesMethods.AverageSales(productSales));
        message = "Total Sales: " + salesMethods.GetProductSales(productSales) + "\n Average Sales: " + roundedAverage + "\n Sales over limit: " + salesMethods.salesOverLimit(productSales) + "\n Sales under Limit: " + salesMethods.salesUnderLimit(productSales);
        output.setText(message);
        jLabel1.setText("Years Processed : 2");
    }//GEN-LAST:event_loadButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String messageSave = "DATA LOG" + "\n **********************\n" + message + "\n**********************";
        Path fileName = Path.of("data.txt");
        try {
            Files.writeString(fileName, messageSave);
            String FileContent = Files.readString(fileName);
            System.out.println(FileContent);

        } catch (IOException e) {
            System.out.println("An error occurred: ");
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        // TODO add your handling code here:
        String messageSave = "DATA LOG" + "\n **********************" + message + "**********************";
        Path fileName = Path.of("data.txt");
        try {
            Files.writeString(fileName, messageSave);
            String FileContent = Files.readString(fileName);
            System.out.println(FileContent);

        } catch (IOException e) {
            System.out.println("An error occurred: ");
        }


    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuExitActionPerformed

    private void menuClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClearActionPerformed
        // TODO add your handling code here:
        output.setText("");
        jLabel1.setText("Years processed:");
    }//GEN-LAST:event_menuClearActionPerformed

    private void menuLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoadActionPerformed
        // TODO add your handling code here:
        long roundedAverage = Math.round(salesMethods.AverageSales(productSales));
        message = "Total Sales: " + salesMethods.GetProductSales(productSales) + "\n Average Sales: " + roundedAverage + "\n Sales over limit: " + salesMethods.salesOverLimit(productSales) + "\n Sales under Limit: " + salesMethods.salesUnderLimit(productSales);
        output.setText(message);
        jLabel1.setText("Years Processed : 2");
    }//GEN-LAST:event_menuLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new processproductSales().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadButton;
    private javax.swing.JMenuItem menuClear;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuLoad;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JTextArea output;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
